### ISSUE TITLE
Error in setup

### ISSUE THREAD

**Issue by shakdwipeea** [shreyans4nahata/WhiteWalker#3]
I am getting this error  
`AttributeError: module 'html.parser' has no attribute 'HTMLParseError'`

**Comment by shreyans4nahata** [comment]
Is it during the server setup?

**Comment by shreyans4nahata** [comment]
@shakdwipeea  Check your python 3  version.  There is a bug while working with python 3.5 and django 1.7 . You can update your django to version 1.8.

**Comment by shakdwipeea** [comment]
It comes during `python manage.py runserver 0.0.0.0:3000 `[Imgur](http://i.imgur.com/ZO0qkZB.png?1)

**Comment by shakdwipeea** [comment]
It works now. I think the requirements.txt should reflect 1.8 version of django

**Comment by shreyans4nahata** [comment]
I have made suitable changes in the requirements.txt file.
This is the official [take](https://github.com/django/django/commit/b07aa52e8a8e4c7fdc7265f75ce2e7992e657ae9) on this [issue](https://code.djangoproject.com/ticket/23763).
